version: '3.9'

services:
  postgres:
    image: postgres:13.0-alpine
    restart: always
    env_file:
      - .env_example
    volumes:
      - pg_data_todolist:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d todoisto" ]
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env_example
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  pg_data_todolist:
