# Generated by Django 4.1.3 on 2023-02-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_launch',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата релиза'),
        ),
    ]
