# Generated by Django 4.1.3 on 2023-02-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_product_date_launch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='house_number',
            field=models.CharField(max_length=255, verbose_name='Номер дома'),
        ),
    ]
