# Generated by Django 4.1.3 on 2023-02-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_alter_provider_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='providers', to='providers.product', verbose_name='Продукты'),
        ),
    ]
